### ISSUE TITLE
RapidMiner Licences

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-rapidminer#1]
I just downloaded the latest version of RapidMiner, in order to inverstigate the status of our plugin. In the meanwhile, RapidMiner has adapted a licencing system, requirering a paid licence in order to use full functionality. A trial licence is also offered, however this limits the functionality. One GB of RAM can be used and ARFF support is not included. 

I am still eager to finish the plugin, but we should evaluate whether the offered functionality is enough for our purposes.

**Comment by joaquinvanschoren** [comment]
They said that their second-to-one version would always(?) be open source
and free to use. Perhaps we should only develop against that?

On Monday, 11 August 2014, janvanrijn notifications@github.com wrote:

> I just downloaded the latest version of RapidMiner, in order to
> inverstigate the status of our plugin. In the meanwhile, RapidMiner has
> adapted a licencing system, requirering a paid licence in order to use full
> functionality. A trial licence is also offered, however this limits the
> functionality. One GB of RAM can be used and ARFF support is not included.
> 
> I am still eager to finish the plugin, but we should evaluate whether the
> offered functionality is enough for our purposes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openml/rapidminer/issues/1.

## 

Joaquin Vanschoren
about me http://www.win.tue.nl/~jvanscho/

**Comment by vumaasha** [comment]
Yes. RapidMiner 5 should be still open source. when RapidMiner 7 becomes available, 6 will become open source.
