### ISSUE TITLE
Gradle build failing

### ISSUE THREAD

**Issue by LuudJanssen** [openml/openml-rapidminer#6]
When I'm in the Experimenter folder and I run "./gradlew build" two tests fail with the following error: `org.openml.apiconnector.io.ApiException: Authentication failed`. I reckoned this has to do with the authentication being wrong, so I added a file called `config` to `~/.openml/` with the contents being: `apikey=[...]`. However, that didn't solve the problem. Am I putting the config file in the wrong place? Or am I running the wrong command? Thanks

**Comment by LuudJanssen** [comment]
I got it working by running "./gradlew installExtension" in the "OpenmlConnector" folder, though documentation could mention this

**Comment by joaquinvanschoren** [comment]
Thanks, Luud!

I added a readme to the main folder with your very helpful instructions.
